name: CI Job

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get -y install ffmpeg libsdl2-2.0-0 adb \
       gcc git pkg-config meson ninja-build \
       libavcodec-dev libavformat-dev libavutil-dev \
       libsdl2-dev openjdk-8-jdk python3-pip \
       mingw-w64 mingw-w64-tools android-tools-adb
    - name: Build scrcpy
      run: bash release.sh
    - uses: actions/upload-artifact@v2
      with:
        name: scrcpy
        path: dist/*
